In [1]:
"""
1. 독버섯/식용버섯 분류기
-binary classification (logistic, knn 성능 비교)
-데이터 전처리
-트레이닝/테스트(70:30)
-상관분석(시각화)
"""

'\n1. 독버섯/식용버섯 분류기\n-binary classification (logistic, knn 성능 비교)\n-데이터 전처리\n-트레이닝/테스트(70:30)\n-상관분석(시각화)\n'

In [2]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
mushroom = pd.read_csv("agaricus-lepiota.data", header=None)
mushroom

     0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0     p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1     e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2     e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3     p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4     e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
8119  e  k  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  b  c  l
8120  e  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  n  o  p  b  v  l
8121  e  f  s  n  f  n  a  c  b  n  ...  s  o  o  p  o  o  p  b  c  l
8122  p  k  y  n  f  y  f  c  n  b  ...  k  w  w  p  w  o  e  w  v  l
8123  e  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  o  c  l

[8124 rows x 23 columns]

In [4]:
#poisonous = 1, edible = 0
mushroom[0] = np.where(mushroom[0]=='p','1','0')
mushroom

     0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0     1  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1     0  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2     0  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3     1  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4     0  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
8119  0  k  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  b  c  l
8120  0  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  n  o  p  b  v  l
8121  0  f  s  n  f  n  a  c  b  n  ...  s  o  o  p  o  o  p  b  c  l
8122  1  k  y  n  f  y  f  c  n  b  ...  k  w  w  p  w  o  e  w  v  l
8123  0  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  o  c  l

[8124 rows x 23 columns]

In [5]:
mushroom[4] = np.where(mushroom[4]=='f','1','0')
mushroom[6] = np.where(mushroom[6]=='f','1','0')
mushroom[7] = np.where(mushroom[7]=='c','1','0')
mushroom[8] = np.where(mushroom[8]=='b','1','0')
mushroom[10] = np.where(mushroom[10]=='e','1','0')

In [6]:
mushroom

     0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0     1  x  s  n  0  p  1  1  0  k  ...  s  w  w  p  w  o  p  k  s  u
1     0  x  s  y  0  a  1  1  1  k  ...  s  w  w  p  w  o  p  n  n  g
2     0  b  s  w  0  l  1  1  1  n  ...  s  w  w  p  w  o  p  n  n  m
3     1  x  y  w  0  p  1  1  0  n  ...  s  w  w  p  w  o  p  k  s  u
4     0  x  s  g  1  n  1  0  1  k  ...  s  w  w  p  w  o  e  n  a  g
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
8119  0  k  s  n  1  n  0  1  1  y  ...  s  o  o  p  o  o  p  b  c  l
8120  0  x  s  n  1  n  0  1  1  y  ...  s  o  o  p  n  o  p  b  v  l
8121  0  f  s  n  1  n  0  1  1  n  ...  s  o  o  p  o  o  p  b  c  l
8122  1  k  y  n  1  y  1  1  0  b  ...  k  w  w  p  w  o  e  w  v  l
8123  0  x  s  n  1  n  0  1  1  y  ...  s  o  o  p  o  o  p  o  c  l

[8124 rows x 23 columns]

In [7]:
mushroom.drop(16, axis=1, inplace=True)

In [8]:
mushroom

     0  1  2  3  4  5  6  7  8  9   ... 12 13 14 15 17 18 19 20 21 22
0     1  x  s  n  0  p  1  1  0  k  ...  s  s  w  w  w  o  p  k  s  u
1     0  x  s  y  0  a  1  1  1  k  ...  s  s  w  w  w  o  p  n  n  g
2     0  b  s  w  0  l  1  1  1  n  ...  s  s  w  w  w  o  p  n  n  m
3     1  x  y  w  0  p  1  1  0  n  ...  s  s  w  w  w  o  p  k  s  u
4     0  x  s  g  1  n  1  0  1  k  ...  s  s  w  w  w  o  e  n  a  g
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
8119  0  k  s  n  1  n  0  1  1  y  ...  s  s  o  o  o  o  p  b  c  l
8120  0  x  s  n  1  n  0  1  1  y  ...  s  s  o  o  n  o  p  b  v  l
8121  0  f  s  n  1  n  0  1  1  n  ...  s  s  o  o  o  o  p  b  c  l
8122  1  k  y  n  1  y  1  1  0  b  ...  s  k  w  w  w  o  e  w  v  l
8123  0  x  s  n  1  n  0  1  1  y  ...  s  s  o  o  o  o  p  o  c  l

[8124 rows x 22 columns]

In [9]:
mushroom_dummies = pd.get_dummies(data=mushroom, columns=[1,2,3,5,9,11,12,13,14,15,17,18,19,20,21,22], prefix=[1,2,3,5,9,11,12,13,14,15,17,18,19,20,21,22])
mushroom_dummies

,0,4,6,7,8,10,1_b,1_c,1_f,1_k,...,21_s,21_v,21_y,22_d,22_g,22_l,22_m,22_p,22_u,22_w
0,1,0,1,1,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
1,0,0,1,1,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,1,0,1,1,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
4,0,1,1,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,1,0,1,1,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8120,0,1,0,1,1,1,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
8121,0,1,0,1,1,1,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
8122,1,1,1,1,0,0,0,0,0,1,...,0,1,0,0,0,1,0,0,0,0
8123,0,1,0,1,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [12]:
xdata = mushroom_dummies.iloc[:,1:]
xdata
ydata = mushroom_dummies.iloc[:,0]
ydata

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: 0, Length: 8124, dtype: object

In [13]:
xdata.shape #(8124, 111)
ydata.shape #(8124,)

(8124,)

In [14]:
xtrain, xtest, ytrain, ytest = train_test_split(xdata, ydata, random_state=42, train_size=0.7)

## Logistic classification

In [16]:
res = LogisticRegression().fit(xtrain, ytrain)

C:\Users\student\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [17]:
print('training set score: {:.3f}'.format(res.score(xtrain,ytrain)))
print('test set score: {:.3f}'.format(res.score(xtest,ytest)))

training set score: 1.000
test set score: 1.000

## knn

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
clf = KNeighborsClassifier(n_neighbors=3)

In [21]:
res = clf.fit(xtrain, ytrain)

In [22]:
clf.predict(xtest)

array(['0', '1', '1', ..., '1', '0', '0'], dtype=object)

In [23]:
print("training set score: {:.3f}".format(res.score(xtrain,ytrain)))
print("test set score: {:.3f}".format(res.score(xtest,ytest)))

training set score: 1.000
test set score: 1.000